export const VERIFY_RECAPTCHA = 'app/Payments/VERIFY_RECAPTCHA';
export const VERIFY_RECAPTCHA_FAILURE = 'app/Payments/VERIFY_RECAPTCHA_FAILURE';
export const VERIFY_RECAPTCHA_SUCCESS = 'app/Payments/VERIFY_RECAPTCHA_SUCCESS';
