export const CLEAR_ALERTS = 'app/PullRequests/CLEAR_ALERTS';

export const CREATE_PULL_REQUEST = 'app/PullRequests/CREATE_PULL_REQUEST';
export const CREATE_PULL_REQUEST_FAILURE =
  'app/PullRequests/CREATE_PULL_REQUEST_FAILURE';
export const CREATE_PULL_REQUEST_SUCCESS =
  'app/PullRequests/CREATE_PULL_REQUEST_SUCCESS';

export const DELETE_PULL_REQUEST = 'app/PullRequests/DELETE_PULL_REQUEST';
export const DELETE_PULL_REQUEST_FAILURE =
  'app/PullRequests/DELETE_PULL_REQUEST_FAILURE';
export const DELETE_PULL_REQUEST_SUCCESS =
  'app/PullRequests/DELETE_PULL_REQUEST_SUCCESS';

export const FETCH_GITHUB_PULL_REQUESTS =
  'app/PullRequests/FETCH_GITHUB_PULL_REQUESTS';
export const FETCH_GITHUB_PULL_REQUESTS_FAILURE =
  'app/PullRequests/FETCH_GITHUB_PULL_REQUESTS_FAILURE';
export const FETCH_GITHUB_PULL_REQUESTS_SUCCESS =
  'app/PullRequests/FETCH_GITHUB_PULL_REQUESTS_SUCCESS';

export const FETCH_USER_PULL_REQUESTS =
  'app/PullRequests/FETCH_USER_PULL_REQUESTS';
export const FETCH_USER_PULL_REQUESTS_FAILURE =
  'app/PullRequests/FETCH_USER_PULL_REQUESTS_FAILURE';
export const FETCH_USER_PULL_REQUESTS_SUCCESS =
  'app/PullRequests/FETCH_USER_PULL_REQUESTS_SUCCESS';

export const HANDLE_STEP = 'app/PullRequests/HANDLE_STEP';

export const IMPORT_PULL_REQUEST = 'app/PullRequests/IMPORT_PULL_REQUEST';
export const IMPORT_PULL_REQUEST_FAILURE =
  'app/PullRequests/IMPORT_PULL_REQUEST_FAILURE';
export const IMPORT_PULL_REQUEST_SUCCESS =
  'app/PullRequests/IMPORT_PULL_REQUEST_SUCCESS';

export const INPUT_CHANGE = 'app/PullRequests/INPUT_CHANGE';

export const INPUT_ERROR = 'app/PullRequests/INPUT_ERROR';

export const RESET_STATE = 'app/PullRequests/RESET_STATE';
