export const FETCH_USER_PROFILE = 'app/Stats/FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_FAILURE =
  'app/Stats/FETCH_USER_PROFILE_FAILURE';
export const FETCH_USER_PROFILE_SUCCESS =
  'app/Stats/FETCH_USER_PROFILE_SUCCESS';
