export const FETCH_COMPANIES = 'app/Main/FETCH_COMPANIES';
export const FETCH_COMPANIES_FAILURE = 'app/Main/FETCH_COMPANIES_FAILURE';
export const FETCH_COMPANIES_SUCCESS = 'app/Main/FETCH_COMPANIES_SUCCESS';
