export const FETCH_WATCH_LIST = 'app/Main/FETCH_WATCH_LIST';
export const FETCH_WATCH_LIST_FAILURE = 'app/Main/FETCH_WATCH_LIST_FAILURE';
export const FETCH_WATCH_LIST_SUCCESS = 'app/Main/FETCH_WATCH_LIST_SUCCESS';

export const CLOSE_MODAL_STATE = 'app/Main/CLOSE_MODAL_STATE';
export const OPEN_MODAL_STATE = 'app/Main/OPEN_MODAL_STATE';

export const UPDATE_PAYMENT_MODAL = 'app/Main/UPDATE_PAYMENT_MODAL';
