export const CHANGE_INPUT = 'app/CompanySignUp/CHANGE_INPUT';

export const CHANGE_VIEW = 'app/CompanySignUp/CHANGE_VIEW';

export const CLEAR_ALERTS = 'app/CompanySignUp/CLEAR_ALERTS';

export const FETCH_CONTRACT = 'app/CompanySignUp/FETCH_CONTRACT';
export const FETCH_CONTRACT_FAILURE =
  'app/CompanySignUp/FETCH_CONTRACT_FAILURE';
export const FETCH_CONTRACT_SUCCESS =
  'app/CompanySignUp/FETCH_CONTRACT_SUCCESS';

export const FETCH_QUESTIONS = 'app/CompanySignUp/FETCH_QUESTIONS';
export const FETCH_QUESTIONS_FAILURE =
  'app/CompanySignUp/FETCH_QUESTIONS_FAILURE';
export const FETCH_QUESTIONS_SUCCESS =
  'app/CompanySignUp/FETCH_QUESTIONS_SUCCESS';

export const INPUT_ERROR = 'app/CompanySignUp/INPUT_ERROR';

export const RESET_STATE = 'app/CompanySignUp/RESET_STATE';

export const SUBMIT_COMPANY_RESPONSE =
  'app/CompanySignUp/SUBMIT_COMPANY_RESPONSE';
export const SUBMIT_COMPANY_RESPONSE_FAILURE =
  'app/CompanySignUp/SUBMIT_COMPANY_RESPONSE_FAILURE';
export const SUBMIT_COMPANY_RESPONSE_SUCCESS =
  'app/CompanySignUp/SUBMIT_COMPANY_RESPONSE_SUCCESS';

export const SUBMIT_CONTRACT_ACCEPTED =
  'app/CompanySignUp/SUBMIT_CONTRACT_ACCEPTED';
export const SUBMIT_CONTRACT_ACCEPTED_FAILURE =
  'app/CompanySignUp/SUBMIT_CONTRACT_ACCEPTED_FAILURE';
export const SUBMIT_CONTRACT_ACCEPTED_SUCCESS =
  'app/CompanySignUp/SUBMIT_CONTRACT_ACCEPTED_SUCCESS';
