export const FETCH_FILTER_OPTIONS = 'app/Overview/FETCH_FILTER_OPTIONS';
export const FETCH_FILTER_OPTIONS_FAILURE =
  'app/Overview/FETCH_FILTER_OPTIONS_FAILURE';
export const FETCH_FILTER_OPTIONS_SUCCESS =
  'app/Overview/FETCH_FILTER_OPTIONS_SUCCESS';

export const RESET_STATE = 'app/Overview/RESET_STATE';
