export const FETCH_ORGANIZATION_OPTIONS =
  'app/Overview/FETCH_ORGANIZATION_OPTIONS';
export const FETCH_ORGANIZATION_OPTIONS_FAILURE =
  'app/Overview/FETCH_ORGANIZATION_OPTIONS_FAILURE';
export const FETCH_ORGANIZATION_OPTIONS_SUCCESS =
  'app/Overview/FETCH_ORGANIZATION_OPTIONS_SUCCESS';

export const RESET_STATE = 'app/Overview/RESET_STATE';
