export const FETCH_JOBS_BOARD = 'app/JobsBoard/FETCH_JOBS_BOARD';
export const FETCH_JOBS_BOARD_FAILURE =
  'app/JobsBoard/FETCH_JOBS_BOARD_FAILURE';
export const FETCH_JOBS_BOARD_SUCCESS =
  'app/JobsBoard/FETCH_JOBS_BOARD_SUCCESS';
