export const FETCH_ACTIVE_USER = 'app/Auth/FETCH_ACTIVE_USER';
export const FETCH_ACTIVE_USER_SUCCESS = 'app/Auth/FETCH_ACTIVE_USER_SUCCESS';
export const FETCH_ACTIVE_USER_FAILURE = 'app/Auth/FETCH_ACTIVE_USER_FAILURE';

export const SEARCH_ORGANIZATIONS = 'app/Auth/SEARCH_ORGANIZATIONS';
export const SEARCH_ORGANIZATIONS_SUCCESS =
  'app/Auth/SEARCH_ORGANIZATIONS_SUCCESS';
export const SEARCH_ORGANIZATIONS_FAILURE =
  'app/Auth/SEARCH_ORGANIZATIONS_FAILURE';

export const SIGNIN = 'app/Auth/SIGNIN';
export const SIGNIN_FAILURE = 'app/Auth/SIGNIN_FAILURE';
export const SIGNIN_SUCCESS = 'app/Auth/SIGNIN_SUCCESS';

export const SIGNOUT = 'app/Auth/SIGNOUT';
export const SIGNOUT_FAILURE = 'app/Auth/SIGNOUT_FAILURE';
export const SIGNOUT_SUCCESS = 'app/Auth/SIGNOUT_SUCCESS';

export const UPDATE_ACTIVE_USER = 'app/Auth/UPDATE_ACTIVE_USER';
