export const CHANGE_INPUT = 'app/Jobs/CHANGE_INPUT';

export const CHANGE_VIEW = 'app/Jobs/CHANGE_VIEW';

export const FETCH_QUESTIONS = 'apps/Jobs/FETCH_QUESTIONS';
export const FETCH_QUESTIONS_FAILURE = 'apps/Jobs/FETCH_QUESTIONS_FAILURE';
export const FETCH_QUESTIONS_SUCCESS = 'apps/Jobs/FETCH_QUESTIONS_SUCCESS';

export const SUBMIT_JOB_INFO = 'app/Jobs/SUBMIT_JOB_INFO';
export const SUBMIT_JOB_INFO_FAILURE = 'app/Jobs/SUBMIT_JOB_INFO_FAILURE';
export const SUBMIT_JOB_INFO_SUCCESS = 'app/Jobs/SUBMIT_JOB_INFO_SUCCESS';
