export const CHANGE_INPUT = 'app/Jobs/CHANGE_INPUT';

export const CHANGE_VIEW = 'app/Jobs/CHANGE_VIEW';

export const FETCH_QUESTIONS = 'apps/Jobs/FETCH_QUESTIONS';
export const FETCH_QUESTIONS_FAILURE = 'apps/Jobs/FETCH_QUESTIONS_FAILURE';
export const FETCH_QUESTIONS_SUCCESS = 'apps/Jobs/FETCH_QUESTIONS_SUCCESS';

export const RESET_STATE = 'app/Jobs/RESET_STATE';

export const SUBMIT_USER_RESPONSE = 'app/Jobs/SUBMIT_USER_RESPONSE';
export const SUBMIT_USER_RESPONSE_FAILURE =
  'app/Jobs/SUBMIT_USER_RESPONSE_FAILURE';
export const SUBMIT_USER_RESPONSE_SUCCESS =
  'app/Jobs/SUBMIT_USER_RESPONSE_SUCCESS';
