export const FETCH_HOME_PAGE_STATS = 'app/HomePage/FETCH_HOME_PAGE_STATS';
export const FETCH_HOME_PAGE_STATS_FAILURE =
  'app/HomePage/FETCH_HOME_PAGE_STATS_FAILURE';
export const FETCH_HOME_PAGE_STATS_SUCCESS =
  'app/HomePage/FETCH_HOME_PAGE_STATS_SUCCESS';

export const SEND_CONTACT = 'app/HomePage/SEND_CONTACT';
export const SEND_CONTACT_FAILURE = 'app/HomePage/SEND_CONTACT_FAILURE';
export const SEND_CONTACT_SUCCESS = 'app/HomePage/SEND_CONTACT_SUCCESS';
