export const FETCH_DASHBOARD_STATS = 'app/Stats/FETCH_DASHBOARD_STATS';
export const FETCH_DASHBOARD_STATS_FAILURE =
  'app/Stats/FETCH_DASHBOARD_STATS_FAILURE';
export const FETCH_DASHBOARD_STATS_SUCCESS =
  'app/Stats/FETCH_DASHBOARD_STATS_SUCCESS';
